// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_ard
List cpp_ard(NumericVector X, NumericMatrix Yr, bool intercept, int nburn, int npost, SEXP seed, bool verbose, int printevery, int chain_index);
RcppExport SEXP _BMIselect_cpp_ard(SEXP XSEXP, SEXP YrSEXP, SEXP interceptSEXP, SEXP nburnSEXP, SEXP npostSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP printeverySEXP, SEXP chain_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< int >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< int >::type npost(npostSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type printevery(printeverySEXP);
    Rcpp::traits::input_parameter< int >::type chain_index(chain_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ard(X, Yr, intercept, nburn, npost, seed, verbose, printevery, chain_index));
    return rcpp_result_gen;
END_RCPP
}
// cpp_horseshoe
List cpp_horseshoe(NumericVector X, NumericMatrix Yr, bool intercept, int nburn, int npost, SEXP seed, bool verbose, int printevery, int chain_index);
RcppExport SEXP _BMIselect_cpp_horseshoe(SEXP XSEXP, SEXP YrSEXP, SEXP interceptSEXP, SEXP nburnSEXP, SEXP npostSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP printeverySEXP, SEXP chain_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< int >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< int >::type npost(npostSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type printevery(printeverySEXP);
    Rcpp::traits::input_parameter< int >::type chain_index(chain_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_horseshoe(X, Yr, intercept, nburn, npost, seed, verbose, printevery, chain_index));
    return rcpp_result_gen;
END_RCPP
}
// cpp_multi_laplace
List cpp_multi_laplace(NumericVector X, NumericMatrix Yr, bool intercept, double h, double v, int nburn, int npost, SEXP seed, bool verbose, int printevery, int chain_index);
RcppExport SEXP _BMIselect_cpp_multi_laplace(SEXP XSEXP, SEXP YrSEXP, SEXP interceptSEXP, SEXP hSEXP, SEXP vSEXP, SEXP nburnSEXP, SEXP npostSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP printeverySEXP, SEXP chain_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< int >::type npost(npostSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type printevery(printeverySEXP);
    Rcpp::traits::input_parameter< int >::type chain_index(chain_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_multi_laplace(X, Yr, intercept, h, v, nburn, npost, seed, verbose, printevery, chain_index));
    return rcpp_result_gen;
END_RCPP
}
// cpp_reg_horseshoe
List cpp_reg_horseshoe(NumericVector X, NumericMatrix Yr, bool intercept, double p0, double nu, double s, int nburn, int npost, SEXP seed, bool verbose, int printevery, int chain_index);
RcppExport SEXP _BMIselect_cpp_reg_horseshoe(SEXP XSEXP, SEXP YrSEXP, SEXP interceptSEXP, SEXP p0SEXP, SEXP nuSEXP, SEXP sSEXP, SEXP nburnSEXP, SEXP npostSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP printeverySEXP, SEXP chain_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< int >::type npost(npostSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type printevery(printeverySEXP);
    Rcpp::traits::input_parameter< int >::type chain_index(chain_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_reg_horseshoe(X, Yr, intercept, p0, nu, s, nburn, npost, seed, verbose, printevery, chain_index));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sl_loglik_check
NumericMatrix cpp_sl_loglik_check(NumericVector X, NumericMatrix Yr, NumericVector lambda2_, double sigma2, IntegerVector Z_);
RcppExport SEXP _BMIselect_cpp_sl_loglik_check(SEXP XSEXP, SEXP YrSEXP, SEXP lambda2_SEXP, SEXP sigma2SEXP, SEXP Z_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda2_(lambda2_SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Z_(Z_SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sl_loglik_check(X, Yr, lambda2_, sigma2, Z_));
    return rcpp_result_gen;
END_RCPP
}
// cpp_spike_laplace
List cpp_spike_laplace(NumericVector X, NumericMatrix Yr, bool intercept, double a, double b, int nburn, int npost, SEXP seed, bool verbose, int printevery, int chain_index);
RcppExport SEXP _BMIselect_cpp_spike_laplace(SEXP XSEXP, SEXP YrSEXP, SEXP interceptSEXP, SEXP aSEXP, SEXP bSEXP, SEXP nburnSEXP, SEXP npostSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP printeverySEXP, SEXP chain_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< int >::type npost(npostSEXP);
    Rcpp::traits::input_parameter< SEXP >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type printevery(printeverySEXP);
    Rcpp::traits::input_parameter< int >::type chain_index(chain_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_spike_laplace(X, Yr, intercept, a, b, nburn, npost, seed, verbose, printevery, chain_index));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BMIselect_cpp_ard", (DL_FUNC) &_BMIselect_cpp_ard, 9},
    {"_BMIselect_cpp_horseshoe", (DL_FUNC) &_BMIselect_cpp_horseshoe, 9},
    {"_BMIselect_cpp_multi_laplace", (DL_FUNC) &_BMIselect_cpp_multi_laplace, 11},
    {"_BMIselect_cpp_reg_horseshoe", (DL_FUNC) &_BMIselect_cpp_reg_horseshoe, 12},
    {"_BMIselect_cpp_sl_loglik_check", (DL_FUNC) &_BMIselect_cpp_sl_loglik_check, 5},
    {"_BMIselect_cpp_spike_laplace", (DL_FUNC) &_BMIselect_cpp_spike_laplace, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_BMIselect(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
