# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ard <- function(X, Yr, intercept, nburn, npost, seed, verbose, printevery, chain_index) {
    .Call(`_BMIselect_cpp_ard`, X, Yr, intercept, nburn, npost, seed, verbose, printevery, chain_index)
}

cpp_horseshoe <- function(X, Yr, intercept, nburn, npost, seed, verbose, printevery, chain_index) {
    .Call(`_BMIselect_cpp_horseshoe`, X, Yr, intercept, nburn, npost, seed, verbose, printevery, chain_index)
}

cpp_multi_laplace <- function(X, Yr, intercept, h, v, nburn, npost, seed, verbose, printevery, chain_index) {
    .Call(`_BMIselect_cpp_multi_laplace`, X, Yr, intercept, h, v, nburn, npost, seed, verbose, printevery, chain_index)
}

cpp_reg_horseshoe <- function(X, Yr, intercept, p0, nu, s, nburn, npost, seed, verbose, printevery, chain_index) {
    .Call(`_BMIselect_cpp_reg_horseshoe`, X, Yr, intercept, p0, nu, s, nburn, npost, seed, verbose, printevery, chain_index)
}

cpp_sl_loglik_check <- function(X, Yr, lambda2_, sigma2, Z_) {
    .Call(`_BMIselect_cpp_sl_loglik_check`, X, Yr, lambda2_, sigma2, Z_)
}

cpp_spike_laplace <- function(X, Yr, intercept, a, b, nburn, npost, seed, verbose, printevery, chain_index) {
    .Call(`_BMIselect_cpp_spike_laplace`, X, Yr, intercept, a, b, nburn, npost, seed, verbose, printevery, chain_index)
}

